import {
  Column,
  CreateDateColumn,
  Entity,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import type {
  DeliveryFailReason,
  OrderSource,
  OrderStatus,
  PaymentStatus,
  SubscriptionFrequency,
  VehicleKind,
  ZoneKind,
} from '@milkman/shared';

@Entity('subscriptions')
export class Subscription {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'customer_id', type: 'uuid' })
  customerId: string;

  @Column({ name: 'address_id', type: 'uuid' })
  addressId: string;

  @Column({ name: 'packs_per_delivery', type: 'integer' })
  packsPerDelivery: number;

  @Column({ type: 'enum', enum: ['daily', 'alternate_days', 'custom_weekdays'] })
  frequency: SubscriptionFrequency;

  /** 0=Sun..6=Sat; only used with custom_weekdays. */
  @Column({ type: 'smallint', array: true, default: '{}' })
  weekdays: number[];

  @Column({ default: false })
  paused: boolean;

  @Column({ name: 'starts_on', type: 'date' })
  startsOn: string;

  @Column({ name: 'ends_on', type: 'date', nullable: true })
  endsOn: string | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;
}

@Entity('orders')
export class Order {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /** e.g. MLK-1042, generated by the DB sequence. */
  @Column({ type: 'text', unique: true })
  reference: string;

  @Column({ name: 'customer_id', type: 'uuid' })
  customerId: string;

  @Column({ name: 'address_id', type: 'uuid', nullable: true })
  addressId: string | null;

  @Column({ name: 'subscription_id', type: 'uuid', nullable: true })
  subscriptionId: string | null;

  @Column({ type: 'enum', enum: ['website', 'whatsapp', 'call', 'admin', 'subscription'], default: 'website' })
  source: OrderSource;

  @Column({ type: 'enum', enum: ['new', 'confirmed', 'packed', 'out_for_delivery', 'delivered', 'failed', 'cancelled'], default: 'new' })
  status: OrderStatus;

  @Column({ name: 'payment_status', type: 'enum', enum: ['pending', 'paid', 'partially_paid', 'failed', 'refunded', 'expired'], default: 'pending' })
  paymentStatus: PaymentStatus;

  @Column({ type: 'integer' })
  packs: number;

  @Column({ name: 'total_ksh', type: 'integer' })
  totalKsh: number;

  /** GeoJSON Point (WGS-84); written with raw ST_MakePoint SQL. */
  @Column({ name: 'delivery_point', type: 'geometry', spatialFeatureType: 'Point', srid: 4326 })
  deliveryPoint: { type: 'Point'; coordinates: [number, number] };

  @Column({ type: 'enum', enum: ['bicycle', 'motorcycle', 'out_of_zone'] })
  zone: ZoneKind;

  @Column({ type: 'enum', enum: ['bicycle', 'motorcycle'], nullable: true })
  vehicle: VehicleKind | null;

  @Column({ name: 'delivery_date', type: 'date' })
  deliveryDate: string;

  @Column({ type: 'text', nullable: true })
  note: string | null;

  @Column({ name: 'cancelled_reason', type: 'text', nullable: true })
  cancelledReason: string | null;

  @Column({ name: 'failed_reason', type: 'enum', enum: ['door_locked', 'unreachable', 'other'], nullable: true })
  failedReason: DeliveryFailReason | null;

  @Column({ name: 'placed_at', type: 'timestamptz', default: () => 'now()' })
  placedAt: Date;

  @Column({ name: 'locked_at', type: 'timestamptz', nullable: true })
  lockedAt: Date | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;
}

@Entity('order_items')
export class OrderItem {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id: string;

  @Column({ name: 'order_id', type: 'uuid' })
  orderId: string;

  @Column({ name: 'product_id', type: 'uuid', nullable: true })
  productId: string | null;

  @Column({ name: 'addon_id', type: 'uuid', nullable: true })
  addonId: string | null;

  @Column({ type: 'integer' })
  qty: number;

  @Column({ name: 'unit_price_ksh', type: 'integer' })
  unitPriceKsh: number;

  /** GENERATED ALWAYS AS (qty * unit_price_ksh) STORED — read-only. */
  @Column({ name: 'line_total_ksh', type: 'integer', insert: false, update: false, readonly: true })
  lineTotalKsh: number;
}

@Entity('order_status_history')
export class OrderStatusHistory {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id: string;

  @Column({ name: 'order_id', type: 'uuid' })
  orderId: string;

  @Column({ name: 'from_status', type: 'enum', enum: ['new', 'confirmed', 'packed', 'out_for_delivery', 'delivered', 'failed', 'cancelled'], nullable: true })
  fromStatus: OrderStatus | null;

  @Column({ name: 'to_status', type: 'enum', enum: ['new', 'confirmed', 'packed', 'out_for_delivery', 'delivered', 'failed', 'cancelled'] })
  toStatus: OrderStatus;

  @Column({ name: 'changed_by', type: 'uuid', nullable: true })
  changedBy: string | null;

  @Column({ type: 'text', nullable: true })
  note: string | null;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;
}
